/* GENERATED by scripts/html-to-jsx.py from the captured homepage.
 * Re-run that script rather than editing this file by hand.
 *
 * This is the homepage's own markup, converted attribute for attribute:
 * the design is carried by src/styles/home-extracted.css, which holds the
 * inline styles the capture had scattered through the DOM.
 *
 * Hand-edited since generation: the hero's title/date lockup was replaced by
 * <HeroCard />. The purple beam and the GOA 2027 wordmark stay — they are what
 * the glass refracts, and neither is a video. Re-running the script would put
 * the old lockup back. */

import HeroCard from '../components/HeroCard'

export default function HomeMarkup() {
  return (
    <>
    <div className="css-1lnv2da">
      <div className="css-b45nl7">
        <div className="css-12ixfif">
          <div className="css-1xjgqhw">
            <div className="styles_clipPath__jYDI7">
              <div className="styles_clipPath_wrapper__2EjOL">
                <figure className="styles_clipPath_wrapper_figure__thifo">
                  <div className="css-17r0n4r">
                    <div className="css-4af9ja">
                      <div className="css-ajcbzs">
                      </div>
                      <div className="css-18vcitk">
                      </div>
                    </div>
                    <svg className="css-uwwqev">
                      <defs>
                        <filter id="goo">
                          <feGaussianBlur in="SourceGraphic" stdDeviation="20" result="name">
                          </feGaussianBlur>
                          <feColorMatrix in="name" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 30 -15" result="aab">
                          </feColorMatrix>
                          <feBlend in="SourceGraphic" in2="aab">
                          </feBlend>
                        </filter>
                      </defs>
                    </svg>
                  </div>
                </figure>
              </div>
            </div>
            <HeroCard />
            <div className="styles_content_image__bvRpE css-1t74537">
              <img alt="home-hero-text" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} src="upload/home-hero-text.svg" />
            </div>
          </div>
        </div>
        {/* The venue film — the reel that scrubbed from a tilted card to
            full-bleed, with its Venue film / MUTE bar — was removed on request
            along with the hero's video card. Its motion block in
            useHomeMotion goes with it. */}
        <div id="home-hero-scroll-target" className="css-47tmvb">
        </div>
      </div>
    </div>
    <div className="css-wyoub9">
      <div className="css-1h2ozsz">
        <div className="css-edj2ce">
          <template data-dgst="BAILOUT_TO_CLIENT_SIDE_RENDERING">
          </template>
          <div className="css-130dp97">
            <div className="css-dru4ek">
              Rotary Institute 2027, hosted in Goa at ATI ONGC, Goa’s largest convention centre.
            </div>
            <div className="css-dwl3oz">
              Rotary Institute 2027, hosted in Goa at ATI ONGC, Goa’s largest convention centre.
            </div>
          </div>
        </div>
        <div className="css-1ndbw87">
          <div className="styles_content__T0TRn css-1vc0j9z">
            <div className="css-v905pd">
              <div className="css-16oy8lz">
                <div className="css-14ba2z6">
                  <div className="css-18tlmaw">
                    <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                      <img alt="projects" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent' }} src="/media/venue-prithvi.jpg" />
                      <img alt="projects" width="1920" height="1080" decoding="async" data-nimg="1" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ color: 'transparent' }} sizes="100vw" src="/media/venue-prithvi.jpg" />
                    </div>
                  </div>
                </div>
                <div className="css-k8vowv">
                </div>
                <div className="css-1ot8zsz">
                  <div className="css-56dpd6">
                    <div className="css-32652j">
                      <div className="Container_container_grid__LWYyb css-l4y3fm">
                        <div className="css-gu32ue">
                          <div className="css-1gpgow9">
                            <h3 className="css-zwnf0y">
                              <span className="css-1gs4s93">
                                The venue
                              </span>
                              ATI ONGC: one room, every zone, one programme.
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="Container_container_grid__LWYyb css-1j1fgla">
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Fellowship
                            </p>
                          </div>
                        </div>
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Goa
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-e2urn8">
                    <div className="css-1w945i0">
                      <div className="js-project-description css-1as290b">
                        <span className="css-3w1c3c">
                          A tiered auditorium sized for the full Institute, with staging and screens already in place.
                        </span>
                      </div>
                    </div>
                    <div className="Container_container_grid__LWYyb css-i1jpw7">
                      <div className="css-9cvvru">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Fellowship
                          </p>
                        </div>
                      </div>
                      <div className="css-14sevk6">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Goa
                          </p>
                        </div>
                      </div>
                      <div className="css-4pzbv1">
                        <div className="css-99wu2y">
                          <div className="js-project-description css-1as290b">
                            <span className="css-3w1c3c">
                              A tiered auditorium sized for the full Institute, with staging and screens already in place.
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="css-jl85b3">
                        <div className="css-wx989e">
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                          </button>
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="css-1y69zf3">
                <div className="css-14ba2z6">
                  <div className="css-18tlmaw">
                    <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                      <img alt="projects" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent' }} src="/media/venue-concourse.jpg" />
                      <img alt="projects" loading="lazy" width="1920" height="1080" decoding="async" data-nimg="1" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ color: 'transparent' }} sizes="100vw" src="/media/venue-concourse.jpg" />
                    </div>
                  </div>
                </div>
                <div className="css-k8vowv">
                </div>
                <div className="css-1ot8zsz">
                  <div className="css-56dpd6">
                    <div className="css-32652j">
                      <div className="Container_container_grid__LWYyb css-l4y3fm">
                        <div className="css-gu32ue">
                          <div className="css-1gpgow9">
                            <h3 className="css-zwnf0y">
                              <span className="css-1gs4s93">
                                The venue
                              </span>
                              The concourse: the House of Friendship, under one roof.
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="Container_container_grid__LWYyb css-1j1fgla">
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Fellowship
                            </p>
                          </div>
                        </div>
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Goa
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-e2urn8">
                    <div className="css-1w945i0">
                      <div className="js-project-description css-1as290b">
                        <span className="css-3w1c3c">
                          An exhibition floor between the halls, wide enough for the stalls and for the conversations they start.
                        </span>
                      </div>
                    </div>
                    <div className="Container_container_grid__LWYyb css-i1jpw7">
                      <div className="css-9cvvru">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Fellowship
                          </p>
                        </div>
                      </div>
                      <div className="css-14sevk6">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Goa
                          </p>
                        </div>
                      </div>
                      <div className="css-4pzbv1">
                        <div className="css-99wu2y">
                          <div className="js-project-description css-1as290b">
                            <span className="css-3w1c3c">
                              An exhibition floor between the halls, wide enough for the stalls and for the conversations they start.
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="css-jl85b3">
                        <div className="css-wx989e">
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                          </button>
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="css-1y69zf3">
                <div className="css-14ba2z6">
                  <div className="css-18tlmaw">
                    <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                      <img alt="projects" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent' }} src="/media/venue-hall.jpg" />
                      <img alt="projects" loading="lazy" width="1920" height="1080" decoding="async" data-nimg="1" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ color: 'transparent' }} sizes="100vw" src="/media/venue-hall.jpg" />
                    </div>
                  </div>
                </div>
                <div className="css-k8vowv">
                </div>
                <div className="css-1ot8zsz">
                  <div className="css-56dpd6">
                    <div className="css-32652j">
                      <div className="Container_container_grid__LWYyb css-l4y3fm">
                        <div className="css-gu32ue">
                          <div className="css-1gpgow9">
                            <h3 className="css-zwnf0y">
                              <span className="css-1gs4s93">
                                The venue
                              </span>
                              Breakout halls for GELS, GNLS and Public Image.
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="Container_container_grid__LWYyb css-1j1fgla">
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Institute
                            </p>
                          </div>
                        </div>
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Goa
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-e2urn8">
                    <div className="css-1w945i0">
                      <div className="js-project-description css-1as290b">
                        <span className="css-3w1c3c">
                          Rooms that seat a zone at a time, every one of them within a corridor of the main auditorium.
                        </span>
                      </div>
                    </div>
                    <div className="Container_container_grid__LWYyb css-i1jpw7">
                      <div className="css-9cvvru">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Institute
                          </p>
                        </div>
                      </div>
                      <div className="css-14sevk6">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Goa
                          </p>
                        </div>
                      </div>
                      <div className="css-4pzbv1">
                        <div className="css-99wu2y">
                          <div className="js-project-description css-1as290b">
                            <span className="css-3w1c3c">
                              Rooms that seat a zone at a time, every one of them within a corridor of the main auditorium.
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="css-jl85b3">
                        <div className="css-wx989e">
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                          </button>
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="css-1y69zf3">
                <div className="css-14ba2z6">
                  <div className="css-18tlmaw">
                    <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                      <img alt="projects" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent' }} src="/media/venue-dining.jpg" />
                      <img alt="projects" loading="lazy" width="1920" height="1080" decoding="async" data-nimg="1" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ color: 'transparent' }} sizes="100vw" src="/media/venue-dining.jpg" />
                    </div>
                  </div>
                </div>
                <div className="css-k8vowv">
                </div>
                <div className="css-1ot8zsz">
                  <div className="css-56dpd6">
                    <div className="css-32652j">
                      <div className="Container_container_grid__LWYyb css-l4y3fm">
                        <div className="css-gu32ue">
                          <div className="css-1gpgow9">
                            <h3 className="css-zwnf0y">
                              <span className="css-1gs4s93">
                                The venue
                              </span>
                              Dining and fellowship, on the same campus.
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="Container_container_grid__LWYyb css-1j1fgla">
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Training
                            </p>
                          </div>
                        </div>
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Goa
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-e2urn8">
                    <div className="css-1w945i0">
                      <div className="js-project-description css-1as290b">
                        <span className="css-3w1c3c">
                          A dining hall that turns over the whole Institute, and evenings that need no coach transfer to reach.
                        </span>
                      </div>
                    </div>
                    <div className="Container_container_grid__LWYyb css-i1jpw7">
                      <div className="css-9cvvru">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Training
                          </p>
                        </div>
                      </div>
                      <div className="css-14sevk6">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Goa
                          </p>
                        </div>
                      </div>
                      <div className="css-4pzbv1">
                        <div className="css-99wu2y">
                          <div className="js-project-description css-1as290b">
                            <span className="css-3w1c3c">
                              A dining hall that turns over the whole Institute, and evenings that need no coach transfer to reach.
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="css-jl85b3">
                        <div className="css-wx989e">
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                          </button>
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="css-1y69zf3">
                <div className="css-14ba2z6">
                  <div className="css-18tlmaw">
                    <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                      <img alt="projects" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent' }} src="/media/stay-exterior.jpg" />
                      <img alt="projects" loading="lazy" width="1920" height="1080" decoding="async" data-nimg="1" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ color: 'transparent' }} sizes="100vw" src="/media/stay-exterior.jpg" />
                    </div>
                  </div>
                </div>
                <div className="css-k8vowv">
                </div>
                <div className="css-1ot8zsz">
                  <div className="css-56dpd6">
                    <div className="css-32652j">
                      <div className="Container_container_grid__LWYyb css-l4y3fm">
                        <div className="css-gu32ue">
                          <div className="css-1gpgow9">
                            <h3 className="css-zwnf0y">
                              <span className="css-1gs4s93">
                                The venue
                              </span>
                              Residency blocks: sleep where you sit.
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="Container_container_grid__LWYyb css-1j1fgla">
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Public Image
                            </p>
                          </div>
                        </div>
                        <div className="css-b1qh9y">
                          <div className="css-1tnhvnf">
                            <p className="css-1csbsx5">
                              Goa
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-e2urn8">
                    <div className="css-1w945i0">
                      <div className="js-project-description css-1as290b">
                        <span className="css-3w1c3c">
                          Accommodation on the grounds, so the walk from a GELS session back to your room is a walk.
                        </span>
                      </div>
                    </div>
                    <div className="Container_container_grid__LWYyb css-i1jpw7">
                      <div className="css-9cvvru">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Public Image
                          </p>
                        </div>
                      </div>
                      <div className="css-14sevk6">
                        <div className="css-1tnhvnf">
                          <p className="css-1csbsx5">
                            Goa
                          </p>
                        </div>
                      </div>
                      <div className="css-4pzbv1">
                        <div className="css-99wu2y">
                          <div className="js-project-description css-1as290b">
                            <span className="css-3w1c3c">
                              Accommodation on the grounds, so the walk from a GELS session back to your room is a walk.
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="css-jl85b3">
                        <div className="css-wx989e">
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                              </div>
                            </div>
                          </button>
                          <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                            <div className="css-14om1bk">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                            <div className="css-gyp8mm">
                              <div className="main-icon css-1x3oun">
                                <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                              </div>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="slider-highlight css-1c86153">
              <h3 className="css-1csbsx5">
                The venue
              </h3>
            </div>
            <div className="css-m04x7s">
              <a href="/venue" className="css-1kmvrrj">
                <div className="css-1lpdf6v">
                  <div className="css-bm8kum">
                    <div className="css-l1tuuh">
                      <span className="css-0">
                        See the venue
                      </span>
                    </div>
                  </div>
                </div>
                <div className="css-gyp8mm">
                  <div className="css-bm8kum">
                    <div className="css-l1tuuh">
                      <span className="css-0">
                        See the venue
                      </span>
                    </div>
                  </div>
                </div>
              </a>
            </div>
            <div className="css-lgaqy6">
              <div className="css-wx989e">
                <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                  <div className="css-14om1bk">
                    <div className="main-icon css-1x3oun">
                      <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                    </div>
                  </div>
                  <div className="css-gyp8mm">
                    <div className="main-icon css-1x3oun">
                      <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-left.svg" />
                    </div>
                  </div>
                </button>
                <button className="ProjectSliderActions_icon__5M3_9 css-1sdzwje">
                  <div className="css-14om1bk">
                    <div className="main-icon css-1x3oun">
                      <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                    </div>
                  </div>
                  <div className="css-gyp8mm">
                    <div className="main-icon css-1x3oun">
                      <img alt="icon" loading="lazy" width="14" height="14" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="icons/ic_arrow-right.svg" />
                    </div>
                  </div>
                </button>
              </div>
            </div>
            <div className="css-16jj2xp">
              <div className="css-1apokmj">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div className="styles_worked__ZRqpe css-1tnhvnf">
      <div className="css-0">
        <div className="Container_container_grid__LWYyb styles_worked_main__rjWnX css-7d51i">
          <div className="css-okxi78">
            <div className="css-1du17gw">
              <p className="css-vldh3s">
                We are proud to have worked with
              </p>
            </div>
          </div>
          <div className="css-1yyw0rr">
            <div className="css-1bflysw">
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
              <p className="styles_label__NPZVh js-worked-brand css-10z9ob3">
              </p>
            </div>
          </div>
          <div className="css-ywh6lb">
            <div className="css-cu4xnz">
              <div className="css-1tnhvnf">
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} sizes="auto" src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} sizes="auto" src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} sizes="auto" src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
                <div className="css-1c6heav">
                  <div className="image-placeholder ImagePlaceholder_imagePlaceholder__UW5XD css-pf0bo6">
                    <img alt="logo" loading="eager" width="32" height="32" decoding="async" data-nimg="1" className="" style={{ color: 'transparent', objectFit: 'contain' }} src="/media/placeholder.jpg" />
                    <img alt="logo" loading="lazy" decoding="async" data-nimg="fill" className="ImagePlaceholder_imagePlaceholder__original__CpPiD" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'contain', color: 'transparent' }} src="/media/placeholder.jpg" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div className="css-rqgsqp">
      <div className="css-vp4en7">
        <div className="css-jop0w3">
          <div className="Container_container_grid__LWYyb css-bpizdw">
            <div className="css-3yenu1">
              <div className="css-1xs4ei8">
                <div className="css-112kalm">
                  <h4 className="css-hj2ayb card-title--long">
                    Rotary Institute 2027
                  </h4>
                  <div className="css-16wafc">
                    <div className="css-2ehw24">
                      <p className="css-cg4oga">
                        01
                      </p>
                    </div>
                    <div className="css-zrk7at">
                      <div className="css-eotvpp">
                        <div className="css-10a9grd">
                          <div className="css-1wxd43s">
                            <div className="">
                              <span className="css-3w1c3c">
                                26 · 27 · 28 November
                              </span>
                            </div>
                          </div>
                          <div className="css-jl85b3">
                            <div className="js-service-image css-1crm7gs">
                              <img alt="Rotary Institute 2027" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/event-plenary.jpg" />
                            </div>
                          </div>
                          <div className="css-ml05u1">
                            <div className="">
                              <p className="css-et528z">
                                Three days at ATI ONGC: the inaugural lunch and plenary on the Friday, a full plenary day on the Saturday, and the closing session and valedictory on the Sunday.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-jl85b3">
                    <div className="">
                      <p className="css-1pi8gkn">
                        Three days at ATI ONGC: the inaugural lunch and plenary on the Friday, a full plenary day on the Saturday, and the closing session and valedictory on the Sunday.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="css-19ltxjc">
                  <div className="css-1s3y6l3">
                    <a title="Program schedule - Rotary Institute 2027" href="/schedule#institute">
                      <div className="css-3byrcy">
                        <span className="fix-mask-clip-mask css-1hswejy">
                          <span className="will-change-transform css-13o7eu2">
                            <span className="will-change-transform css-1bx5ylf">
                              <span className="text css-13o7eu2">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                              <span className="text__clone css-rdqqhl">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                            </span>
                          </span>
                        </span>
                        <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                          <div className="css-14om1bk">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                          <div className="css-gyp8mm">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                        </button>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="css-1f44veo">
              <div className="js-service-image css-1crm7gs">
                <img alt="Rotary Institute 2027" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/event-plenary.jpg" />
              </div>
            </div>
            <div className="css-1dzinm5">
              <div className="css-19z4pko">
                <a title="Program schedule - Rotary Institute 2027" href="/schedule#institute">
                  <div className="css-3byrcy">
                    <span className="fix-mask-clip-mask css-1hswejy">
                      <span className="will-change-transform css-13o7eu2">
                        <span className="will-change-transform css-1bx5ylf">
                          <span className="text css-13o7eu2">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                          <span className="text__clone css-rdqqhl">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                        </span>
                      </span>
                    </span>
                    <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                      <div className="css-14om1bk">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                      <div className="css-gyp8mm">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                    </button>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="css-615dn9">
          <div className="Container_container_grid__LWYyb css-bpizdw">
            <div className="css-3yenu1">
              <div className="css-1xs4ei8">
                <div className="css-112kalm">
                  <h4 className="css-hj2ayb">
                    GELS &amp; GNLS
                  </h4>
                  <div className="css-16wafc">
                    <div className="css-2ehw24">
                      <p className="css-cg4oga">
                        02
                      </p>
                    </div>
                    <div className="css-zrk7at">
                      <div className="css-eotvpp">
                        <div className="css-10a9grd">
                          <div className="css-1wxd43s">
                            <div className="">
                              <span className="css-3w1c3c card-sub--long">
                                Governors Elect Learning Seminars &amp; Governors Nominee Learning Seminars<span className="nowrap-dates">23 · 24 · 25 November</span>
                              </span>
                            </div>
                          </div>
                          <div className="css-jl85b3">
                            <div className="js-service-image css-1crm7gs">
                              <img alt="Governors Elect and Governors Nominee Learning Seminars" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/event-exhibition.jpg" />
                            </div>
                          </div>
                          <div className="css-ml05u1">
                            <div className="">
                              <p className="css-et528z">
                                Three days before the Institute opens: the opening session and fellowship dinner on the Tuesday, a full day of learning seminars on the Wednesday, and graduation on the Thursday afternoon.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-jl85b3">
                    <div className="">
                      <p className="css-1pi8gkn">
                        Three days before the Institute opens: the opening session and fellowship dinner on the Tuesday, a full day of learning seminars on the Wednesday, and graduation on the Thursday afternoon.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="css-19ltxjc">
                  <div className="css-1s3y6l3">
                    <a title="Program schedule - GELS and GNLS" href="/schedule#gels-gnls">
                      <div className="css-3byrcy">
                        <span className="fix-mask-clip-mask css-1hswejy">
                          <span className="will-change-transform css-13o7eu2">
                            <span className="will-change-transform css-1bx5ylf">
                              <span className="text css-13o7eu2">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                              <span className="text__clone css-rdqqhl">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                            </span>
                          </span>
                        </span>
                        <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                          <div className="css-14om1bk">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                          <div className="css-gyp8mm">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                        </button>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="css-1f44veo">
              <div className="js-service-image css-1crm7gs">
                <img alt="Governors Elect and Governors Nominee Learning Seminars" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/event-exhibition.jpg" />
              </div>
            </div>
            <div className="css-1dzinm5">
              <div className="css-19z4pko">
                <a title="Program schedule - GELS and GNLS" href="/schedule#gels-gnls">
                  <div className="css-3byrcy">
                    <span className="fix-mask-clip-mask css-1hswejy">
                      <span className="will-change-transform css-13o7eu2">
                        <span className="will-change-transform css-1bx5ylf">
                          <span className="text css-13o7eu2">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                          <span className="text__clone css-rdqqhl">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                        </span>
                      </span>
                    </span>
                    <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                      <div className="css-14om1bk">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                      <div className="css-gyp8mm">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                    </button>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="css-umltmr">
          <div className="Container_container_grid__LWYyb css-bpizdw">
            <div className="css-3yenu1">
              <div className="css-1xs4ei8">
                <div className="css-112kalm">
                  <h4 className="css-hj2ayb">
                    Pre-Institute
                  </h4>
                  <div className="css-16wafc">
                    <div className="css-2ehw24">
                      <p className="css-cg4oga">
                        03
                      </p>
                    </div>
                    <div className="css-zrk7at">
                      <div className="css-eotvpp">
                        <div className="css-10a9grd">
                          <div className="css-1wxd43s">
                            <div className="">
                              <span className="css-3w1c3c card-sub--long">
                                DLF, COL and the Rotaract Seminar<span className="nowrap-dates">25 November</span>
                              </span>
                            </div>
                          </div>
                          <div className="css-jl85b3">
                            <div className="js-service-image css-1crm7gs">
                              <img alt="Pre-Institute Adjunct Seminars" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/venue-hall.jpg" />
                            </div>
                          </div>
                          <div className="css-ml05u1">
                            <div className="">
                              <p className="css-et528z">
                                The adjunct seminars run through the Thursday — District Learning Facilitators, Council on Legislation and Rotaract — running alongside the closing day of GELS and GNLS, the day before the Institute opens.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-jl85b3">
                    <div className="">
                      <p className="css-1pi8gkn">
                        The adjunct seminars run through the Thursday — District Learning Facilitators, Council on Legislation and Rotaract — running alongside the closing day of GELS and GNLS, the day before the Institute opens.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="css-19ltxjc">
                  <div className="css-1s3y6l3">
                    <a title="Program schedule - Pre-Institute Seminars" href="/schedule#pre-institute">
                      <div className="css-3byrcy">
                        <span className="fix-mask-clip-mask css-1hswejy">
                          <span className="will-change-transform css-13o7eu2">
                            <span className="will-change-transform css-1bx5ylf">
                              <span className="text css-13o7eu2">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                              <span className="text__clone css-rdqqhl">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                            </span>
                          </span>
                        </span>
                        <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                          <div className="css-14om1bk">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                          <div className="css-gyp8mm">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                        </button>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="css-1f44veo">
              <div className="js-service-image css-1crm7gs">
                <img alt="Pre-Institute Adjunct Seminars" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/venue-hall.jpg" />
              </div>
            </div>
            <div className="css-1dzinm5">
              <div className="css-19z4pko">
                <a title="Program schedule - Pre-Institute Seminars" href="/schedule#pre-institute">
                  <div className="css-3byrcy">
                    <span className="fix-mask-clip-mask css-1hswejy">
                      <span className="will-change-transform css-13o7eu2">
                        <span className="will-change-transform css-1bx5ylf">
                          <span className="text css-13o7eu2">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                          <span className="text__clone css-rdqqhl">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                        </span>
                      </span>
                    </span>
                    <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                      <div className="css-14om1bk">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                      <div className="css-gyp8mm">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                    </button>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="css-fnivcm">
          <div className="Container_container_grid__LWYyb css-bpizdw">
            <div className="css-3yenu1">
              <div className="css-1xs4ei8">
                <div className="css-112kalm">
                  <h4 className="css-hj2ayb">
                    TRF Events
                  </h4>
                  <div className="css-16wafc">
                    <div className="css-2ehw24">
                      <p className="css-cg4oga">
                        04
                      </p>
                    </div>
                    <div className="css-zrk7at">
                      <div className="css-eotvpp">
                        <div className="css-10a9grd">
                          <div className="css-1wxd43s">
                            <div className="">
                              <span className="css-3w1c3c card-sub--long">
                                TRF Dinner and TRF Seminar<span className="nowrap-dates">25 · 26 November</span>
                              </span>
                            </div>
                          </div>
                          <div className="css-jl85b3">
                            <div className="js-service-image css-1crm7gs">
                              <img alt="TRF Events" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/venue-dining.jpg" />
                            </div>
                          </div>
                          <div className="css-ml05u1">
                            <div className="">
                              <p className="css-et528z">
                                Two events for The Rotary Foundation sit alongside the Institute, on the evening before it opens and on its first morning.
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="css-jl85b3">
                    <div className="">
                      <p className="css-1pi8gkn">
                        Two events for The Rotary Foundation sit alongside the Institute, on the evening before it opens and on its first morning.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="css-19ltxjc">
                  <div className="css-1s3y6l3">
                    <a title="TRF Events - Rotary Institute 2027" href="/trf-events">
                      <div className="css-3byrcy">
                        <span className="fix-mask-clip-mask css-1hswejy">
                          <span className="will-change-transform css-13o7eu2">
                            <span className="will-change-transform css-1bx5ylf">
                              <span className="text css-13o7eu2">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                              <span className="text__clone css-rdqqhl">
                                <p className="css-yh3d0j">
                                  Program schedule
                                </p>
                              </span>
                            </span>
                          </span>
                        </span>
                        <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                          <div className="css-14om1bk">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                          <div className="css-gyp8mm">
                            <div className="main-icon css-1x3oun">
                              <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                            </div>
                          </div>
                        </button>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div className="css-1f44veo">
              <div className="js-service-image css-1crm7gs">
                <img alt="TRF Events" loading="lazy" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', color: 'transparent', willChange: 'transform', scale: '1' }} src="/media/venue-dining.jpg" />
              </div>
            </div>
            <div className="css-1dzinm5">
              <div className="css-19z4pko">
                <a title="TRF Events - Rotary Institute 2027" href="/trf-events">
                  <div className="css-3byrcy">
                    <span className="fix-mask-clip-mask css-1hswejy">
                      <span className="will-change-transform css-13o7eu2">
                        <span className="will-change-transform css-1bx5ylf">
                          <span className="text css-13o7eu2">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                          <span className="text__clone css-rdqqhl">
                            <p className="css-yh3d0j">
                              Program schedule
                            </p>
                          </span>
                        </span>
                      </span>
                    </span>
                    <button className="Service_icon__GNT_0 css-1sjxqp0" type="button" tabIndex={-1} aria-hidden="true">
                      <div className="css-14om1bk">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                      <div className="css-gyp8mm">
                        <div className="main-icon css-1x3oun">
                          <img alt="icon" loading="lazy" width="27" height="18" decoding="async" data-nimg="1" style={{ color: 'transparent' }} src="upload/icon-arrow.svg" />
                        </div>
                      </div>
                    </button>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </>
  )
}
