/* GENERATED by scripts/extract-footer.py from the captured footer.
 * Re-run that script rather than editing this file by hand — except for
 * the link list, which is hand-tended below because the capture points at
 * a site map this app does not have. */

import { useEffect, useRef } from 'react'
import gsap from 'gsap'

import { nav } from '../data/site'
import Wordmark from './Wordmark'

/**
 * The footer's torch.
 *
 * `.css-okmi5b` is a circle five times the width of the wordmark band, filled
 * with a radial gradient that is transparent for its first 4% and navy at 55%
 * by 14% — a veil with a hole in it, clipped to the band by `.css-yl0wbh`.
 * Nothing in the capture moves it, so it sat dead centre and the effect read as
 * a static vignette.
 *
 * Measured on https://iventions.com/: it follows the pointer on X only — the
 * transform's Y stayed at -3600 with the pointer at the top of the band, the
 * bottom of it, and 600px above it — and it eases rather than snapping (a 800px
 * jump was 71% covered at 120ms and settled by ~420ms). X is global: it tracks
 * wherever the pointer is on the page, not only over the footer.
 *
 *   tx = pointerX - bandLeft - bandWidth/2 - circleWidth/2
 *
 * which reproduces the live numbers exactly (pointer 300 -> -4020, 1100 -> -3220
 * against a 1440 band and a 7200 circle).
 */
function useTorch(circleRef, bandRef) {
  useEffect(() => {
    const circle = circleRef.current
    const band = bandRef.current
    if (!circle || !band) return
    if (!window.matchMedia('(pointer: fine)').matches) return

    // offsetWidth, not the rect: the band's parent is scaled 1.01 and transforms
    // are written in unscaled space.
    let bandW = band.offsetWidth
    let circleW = circle.offsetWidth
    const measure = () => {
      bandW = band.offsetWidth
      circleW = circle.offsetWidth
      gsap.set(circle, { y: -circle.offsetHeight / 2 })
    }
    measure()

    const setX = gsap.quickTo(circle, 'x', { duration: 0.5, ease: 'power3' })
    const onMove = (e) => {
      setX(e.clientX - band.getBoundingClientRect().left - bandW / 2 - circleW / 2)
    }
    // Centred until the pointer first moves, which is where the capture leaves it.
    setX(-circleW / 2)

    window.addEventListener('pointermove', onMove, { passive: true })
    window.addEventListener('resize', measure)
    return () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('resize', measure)
    }
  }, [circleRef, bandRef])
}

export default function SiteFooter() {
  const circleRef = useRef(null)
  const bandRef = useRef(null)
  useTorch(circleRef, bandRef)

  return (
    <footer className="Footer_footer__OGBct">
      <div className="Footer_footer_wrapper__s1xpb">
        <div className="css-g1xylv">
          <div className="styles_top__ACp0i css-0">
            <div className="css-11whfq8">
              {/* The capture repeats the mark here at the top of the footer. Dropped
                  on request — the fixed header already carries it on every page. */}
              {/* The capture's award badge (a CSSDA "Website of the Month" the
                  original won) lived here. It renders 0x0 at every width, links
                  to "#", and still carried the CSSDA alt text, so it announced
                  an award this Institute has not won to a screen reader while
                  showing nothing to anyone else. Dropped rather than restyled. */}
            </div>
            <div className="styles_address__xK870">
              <h2 className="Heading_heading__ts0xt css-62lw6g">
                Celebrate Leadership
                &
                Service
              </h2>
              <div className="css-1bp2dcu">
                <div className="css-ducv57">
                  <div className="Paragraph_paragraph__SId_Y css-cgpd9q">
                    Rotary Institute 2027 — Goa
                  </div>
                  <div className="Paragraph_paragraph__SId_Y css-cgpd9q">
                    Zones 4, 5, 6, 7
                    &
                    8
                  </div>
                  <div className="Paragraph_paragraph__SId_Y css-cgpd9q">
                    26 · 27 · 28 November 2027
                  </div>
                </div>
                <div className="css-ducv57">
                  <div className="Paragraph_paragraph__SId_Y css-cgpd9q">
                    Prithvi Convention Centre ONGC - Goa
                  </div>
                  <div className="Paragraph_paragraph__SId_Y css-cgpd9q">
                    Kital, Canaguinim, Goa 403723
                  </div>
                </div>
              </div>
            </div>
            <div className="styles_top_explore__xYaVQ">
              <div className="styles_contents__NARUt">
                <div className="styles_label__TswfE css-0">
                  <h3 className="Label_label__run2v styles_label_text__AEIA4 css-s47lln">
                    Explore
                  </h3>
                </div>
                <div className="styles_contents_menu___Mcbo">
                  {/* Driven from the same `nav` the header menu uses, so the two
                      lists cannot drift apart. The capture shipped nine entries
                      here, three of which were pages this site does not have. */}
                  {nav.map((item) => (
                    <p className="styles_contents_menu_item____gPS css-2aq1xz" key={item.to}>
                      <a target="_self" href={item.to}>
                        <span>{item.label}</span>
                      </a>
                    </p>
                  ))}
                </div>
              </div>
            </div>
            {/* The Connect column (LinkedIn, Instagram) was removed on request. */}
          </div>
          <div className="Container_container_grid__LWYyb styles_bottom__ws_H0 css-l4y3fm">
            {/* The capture links three policies here that this site does not
                publish, so the slot is left empty rather than shipped as dead
                links. */}
            <div className="styles_bottom_privacy__QFgGC" />
            <div className="css-2h3am9">
              <div className="css-0">
                <span className="Label_label__run2v styles_bottom_copyright__G_dC9 css-vopclq">
                  Copyright © Rotary Institute 2027
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="css-x2xxex">
          <div className="css-17a8lww" ref={bandRef}>
            <div className="css-11yncm4">
              <div className="css-iies54">
                <div className="css-1blqm19">
                  {/* The capture leaves this slot empty — it is the band the
                      original mounts its big wordmark into on the client, so
                      HTTrack captured the container and none of its content.
                      The slot is 26.6rem tall at >=75rem and the mark's viewBox
                      is 266 units high, so it lands at exactly its own size. */}
                  <Wordmark className="foot-wordmark" aria-hidden="true" />
                </div>
              </div>
              <div className="css-yl0wbh">
                <div className="css-okmi5b" ref={circleRef}>
                </div>
              </div>
            </div>
          </div>
          <div className="styles_is_on_mobile__VDdAY css-0">
            <span className="Label_label__run2v styles_bottom_copyright__G_dC9 css-vopclq">
              Copyright © Rotary Institute 2027
            </span>
          </div>
        </div>
      </div>
    </footer>
  )
}
