#!/usr/bin/env python3
"""Lift the captured footer out of the mirror, the same way extract-home.py
lifts <main>.

    python scripts/extract-footer.py

Reads  ../website/index.html
Writes ../src/styles/footer.css          (every inline <style> body inside the footer)
       ../src/components/SiteFooter.jsx  (the markup, converted to JSX)

The footer the site had before this was hand-written and did not match the
theme. This is the capture's own <footer class="Footer_footer__OGBct">, so it
carries the theme's grid, type and spacing rather than an approximation of them.

Dead links are the one thing that does not survive verbatim: the capture points
at a dozen .html files that the React app has no route for. Every href is
remapped to a route that exists, and the rows that have no home at all are
dropped in the JSX afterwards rather than shipped as 404s.
"""

import pathlib
import re
import sys
from html.parser import HTMLParser

HERE = pathlib.Path(__file__).resolve().parent
APP = HERE.parent
SRC_HTML = APP.parent / "website" / "index.html"
OUT_CSS = APP / "src" / "styles" / "footer.css"
OUT_JSX = APP / "src" / "components" / "SiteFooter.jsx"

sys.path.insert(0, str(HERE))
import importlib

h2j = importlib.import_module("html-to-jsx".replace("-", "_")) if False else None

# html-to-jsx.py is not importable by name (the hyphen), so load it by path.
import importlib.util

spec = importlib.util.spec_from_file_location("h2j", HERE / "html-to-jsx.py")
h2j = importlib.util.module_from_spec(spec)
spec.loader.exec_module(h2j)

STYLE_RE = re.compile(r"<style\b[^>]*>(.*?)</style>", re.S)

# The capture's footer links at a site map that never got built. Anything not
# listed here is dropped from the rendered list instead of 404-ing.
ROUTES = {
    "about.html": "/about",
    "schedule.html": "/schedule",
    "gels-gnls.html": "/gels-gnls",
    "committee.html": "/committee",
    "hotel-venue.html": "/hotel-venue",
    "#top": "/",
}


def main():
    html = SRC_HTML.read_text(encoding="utf-8", errors="replace")
    i = html.find("<footer")
    if i < 0:
        raise SystemExit("no <footer> in the capture")
    j = html.find("</footer>", i) + len("</footer>")
    seg = html[i:j]

    # 1. the stylesheet, in document order, deduped by rule text
    seen, css = set(), []
    for body in STYLE_RE.findall(seg):
        for rule in re.findall(r"[^{}]+\{[^{}]*\}|@media[^{]+\{(?:[^{}]|\{[^{}]*\})*\}", body):
            r = rule.strip()
            if r and r not in seen:
                seen.add(r)
                css.append(r)
    OUT_CSS.write_text(
        "/* GENERATED by scripts/extract-footer.py from the captured footer.\n"
        " * Every inline <style data-emotion> body the footer carried, in document\n"
        " * order and deduped. Re-run that script rather than editing by hand. */\n\n"
        + "\n".join(css)
        + "\n",
        encoding="utf-8",
    )

    # 2. the markup, minus the style blocks
    markup = STYLE_RE.sub("", seg)
    for dead, live in ROUTES.items():
        markup = markup.replace('href="%s"' % dead, 'href="%s"' % live)

    parser = h2j.ToJSX()
    parser.feed(markup)
    parser.close()
    while parser.open_stack:
        tag = parser.open_stack.pop()
        parser.out.append("%s</%s>" % (parser.pad(), h2j.jsx_tag(tag)))
    body = "\n".join(parser.out)

    OUT_JSX.write_text(
        "/* GENERATED by scripts/extract-footer.py from the captured footer.\n"
        " * Re-run that script rather than editing this file by hand — except for\n"
        " * the link list, which is hand-tended below because the capture points at\n"
        " * a site map this app does not have. */\n\n"
        "export default function SiteFooter() {\n"
        "  return (\n"
        "%s\n"
        "  )\n"
        "}\n" % body,
        encoding="utf-8",
    )
    print("css  %s  %d rules, %d bytes" % (OUT_CSS.name, len(css), OUT_CSS.stat().st_size))
    print("jsx  %s  %d bytes" % (OUT_JSX.name, OUT_JSX.stat().st_size))
    left = sorted(set(re.findall(r'href="([^"]*\.html)"', markup)))
    if left:
        print("STILL DEAD:", left)


if __name__ == "__main__":
    main()
